### ISSUE TITLE
rmw wait error during colcon build

### ISSUE THREAD

**Issue by RajasJ99** [micro-ROS/rmw-microxrcedds#83] opened 2020-11-16 12:17 UTC
![build](https://user-images.githubusercontent.com/33423968/99250528-d6f7ba80-2831-11eb-9509-bef8ff766dda.png)
 Tried to build rmw-microxrcedds fro micro ros demo , but encountered with this error

**Comment by pablogs9** [comment] 2020-11-16 13:32
This function was included in Micro XRCE-DDS Clien in this commit: https://github.com/eProsima/Micro-XRCE-DDS-Client/commit/46907463f4b0a846f114389320b582028b8334c2

As you can see it is in `foxy` branch. Have you tried to update your repositories? 

If you provide a step by step procedure we can replicate the issue. I guess that doing a clean installation of your micro-ROS environment will solve the issue.

I'm closing since it can be solved by updating your micro-ROS repos, please reopen if you can provide a step by step procedure to reproduce the issue.

**Closed by pablogs9** 2020-11-16 13:32 UTC
